### ISSUE TITLE
tests fail all of a sudden: non-matching feature IDs

### ISSUE THREAD

**Issue by fedarko** [fedarko/rankratioviz#64]
introduced with the latest commit to master (https://github.com/fedarko/rankratioviz/commit/399e4647b91272dc102c6f84d910e67fe238c71e).

Through some judicious print statements, it looks like midway through iterating through the main data in the rank plot JSON the `ranked_features_iterator` gets ahead by one, throwing the comparison off.

Commenting out just this assertion solves the problem. Which is a little weird -- you'd think other things (or at least the `x` check) would get thrown off by this, not just this one check.  

I'd expect I'm missing something obvious here, so I can probably get this solved soon.

**Comment by fedarko** [comment]
Weirdly enough, the places where this fails (and this fails at different places when I rerun the tests) seem to have one thing in common: the two ranks that get "conflated" have (as reported in the JSON) identical rank values. Like, even to 16ish decimal points of precision. That seems... wrong. Maybe something I introduced caused this to occasionally do this weird overwriting thing?

Ranks of interest in pseudomonas DEICODE dataset: x: 245 and x: 246; x:259 and x:260.

**Comment by fedarko** [comment]
From inspecting the original ordination file: it looks like the rank values are the same between these pairs, too -- look at lines 267 and 268 in `ordination.txt`. This indicates that this isn't a problem with rankratioviz, at least not entirely -- what I think happened here is that, since these few rank values are literally identical, the order of these ranks can get switched around, and this causes problems in how the test 'expects' the data to be formatted (because the test just assumes the input ordination file is sorted by its first rank -- which it is, in this case -- but there are multiple valid sortings since there are equal first-rank values).

**Comment by fedarko** [comment]
The solution here is either removing the non-rank-0-data (ID, other ranks, etc) check from the main loop over both the JSON features and reference features (not desirable), or adding some code to: first check that the rank 0s are monotonically increasing, then verify that inconsistencies in ID order are due to rank 0 equalities, then go through and check everything.

gonna be a bit of an overhaul, so I'll work on that later this week. not sure why this issue is only coming up now -- my guess is it's due to using the dataframe approach instead of the dict approach for storing data, but it's still sorta odd. The multiple identical rank values between adjacent features in the DEICODE output also seems really weird.

**Comment by cameronmartino** [comment]
@fedarko  It is not impossible to have ranks with the same values repeated. One easy solution might be to check that the order of the rank values is the same instead of the IDs in the unittest?

**Comment by fedarko** [comment]
That's a solid idea, thanks! I'll get this test knocked out ASAP.
