### ISSUE TITLE
Enforce continuous x-axis on log ratio plot

### ISSUE THREAD

**Issue by ssteiche** [fedarko/rankratioviz#80]
Thanks for making this project, it is very nice for interactive interpretation of these data! I am plotting a continuous variable on the log ratio plot, but it draws a separate x-axis tick for each sample measurement and looks to be plotted more like a categorical measurement. I am not sure if this is happening during pandas import stage, or during the plotting steps. I tested my metadata file using the same pandas read_csv line from your code and the column I am working on is read as 'dtype: float64'. I will trying to trace this through the rest of your code, but am less familiar with the downstream plotting packages.

Example of x-axis pasted below:

![image](https://user-images.githubusercontent.com/9448712/55635259-1ebcf180-5775-11e9-9e98-1cd9cbf113f6.png)

**Comment by fedarko** [comment]
Hi, and thanks for using rankratioviz! You're correct, this is a problem --
I've been meaning to add the option (like in Emperor, if you've used that)
for users to mark a given metadata category as categorical or quantitative.
This is discussed a bit in #31.

(Right now, rankratioviz makes the default assumption that every metadata
category is categorical. This should be configurable by the user, or at
least adjustable based on pandas dtype as you mention.)

I actually worked on resolving this problem a bit last night, but wasn't
successful. As far as I can tell the problem boils down to defining a Vega
"signal" for the x-axis' "scale type," and I wasn't able to get a signal to
function in that manner (Vega kept complaining at me :).

I can take another crack at resolving this in the coming days -- if I
figure out a solution, I'll update you on this issue here.

Thanks again for using rankratioviz, and apologies for the trouble!

**Comment by fedarko** [comment]
Actually, looking at your plot more closely I think the "null" points are
what are causing Vega to interpret this as categorical data. It'd still be
good to have an option in rankratioviz to still use a continuous scale in
this situation (maybe with nulls filtered out, or with them displayed
somehow like in this example scatterplot:
https://vega.github.io/vega/examples/scatter-plot-null-values/), though.

I'll see what I can do to address this.

**Comment by ssteiche** [comment]
Hi Marcus,

Thanks so much for the replies! I was wondering if the null values might be causing the issue as well. 
When I looked at the QIIME2 redsea example, it seemed that the continuous variables (ie; temperature) are being plotted as such. I went ahead and filtered my own sample metadata file to remove null values for the same variable used in the plot above. I left a screenshot below showing that it is still plotting them like a categorical without nulls.

I can't believe that a software package would complain, they never do that! ;P

If I have some time I'll dig deeper and see if I can learn anything about Vega. I'd be very happy if I can provide any actual help and not only complaints of my own.

![image](https://user-images.githubusercontent.com/9448712/55746722-4b7c3d80-59ef-11e9-8a82-4f01cc97bb4b.png)

**Comment by fedarko** [comment]
Thank you for the offer -- I really appreciate it :) I've been planning on restructuring some of the JavaScript code for rankratioviz, so as a heads up the code in `rankratioviz/support_files/` will probably be moving around in the coming days/weeks (although I don't think the actual logic should change that much).

Regarding your data: hm, that's strange! One thing that stands out to me (not sure if this is actually the problem source, though) is the "space" between the minus sign and the number for a few of these numbers (e.g. for `-16.4324473` and `-15.897`). This could very well just be a font thing, but if there's an actual space between these characters then that might be causing some combination of (QIIME 2, pandas, or Vega) to treat this metadata field as categorical.

I'll keep you posted when I manage to hopefully make headway on this.

**Comment by fedarko** [comment]
Hi @ssteiche,

Can you try reinstalling rankratioviz? I just updated it to treat all sample plot x-axis fields as quantitative, which should fix this problem.

From what I can tell, this problem boiled down to the type of the "initial" x-axis metadata field, which (I think) is what the Vega* libraries were using to determine the x-axis scale type. The new code "forces" Vega to just use quantitative fields. (A downside of this is that categorical fields won't display properly, which is something I want to fix soon. I might have to make some more thorough changes to the code to do that, though.)

Sorry for the delay in getting back to you! Let me know if this works for you, and if not I can try another approach.

**Comment by ssteiche** [comment]
Hi Marcus,
Definitely don't apologize!

It worked beautifully (screen capture below)! Thanks so much for your help. Sorry I couldn't help at all. I'm fairly new to code in general, so it takes me quite a lot of effort to trace back how these functions are running to even attempt a fix. 

Now I know I am getting greedy here, but how would you recommend I could go about exporting anything from the interactive visualization? Ideally I would pull out the actually data points so that I can calculate correlation statistics as well. I have been trying to do this using the Figure3.ipynb notebook at https://github.com/knightlab-analyses/reference-frames/blob/master/ipynb/Figure3.ipynb, but am curious if you think I could utilize your code here directly?

Seriously, huge thanks for making this tool. It's great.

![image](https://user-images.githubusercontent.com/9448712/56759959-fd856a80-674e-11e9-8f54-e278aa0d468e.png)

**Comment by fedarko** [comment]
Hi Seth,
Awesome! I'm super glad that this worked out for you. No worries at all :)

There currently aren't any data exporting options I've explicitly coded into rankratioviz, but it should be feasible to add some code to the visualization interface that exports the data points backing the sample plot. What sort of output format would be useful for you? I'm thinking a tab-separated file (`.tsv`) where each line is a point on the sample scatterplot, and there are columns for Sample ID, current metadata value, and current log ratio (including the IDs of the features involved). This should be pretty simple to throw into something like pandas.

I can see about doing this soon -- shouldn't be too hard to implement.

Thanks for using rankratioviz :)

**Comment by fedarko** [comment]
Going to close this issue for now. The data exporting TODOs are now in #87, and future work on supporting categorical *and* quantitative metadata fields in the sample plot will be done in #11 / #73 / etc.
